name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
            
      - name: write style
        run: npx prettier ./src/ --check

      - name: Build docker
        run: docker build -t ghcr.io/wynazanar/practical_work_osis_3/node:latest ./src/

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker
        run: docker push ghcr.io/wynazanar/practical_work_osis_3/node:latest
        
      - if: failure()
        name: Send telegram message on success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.tgChatId }}
          token: ${{ secrets.tgToken }}
          message: |
              Чот пошло не так... Переделывай!


          
              
   build:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
